services:
  yggdrasil:
    image: docker.io/thallheim/yggdrasil:latest
    hostname: yggdrasil
    container_name: yggdrasil
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - proxynet
    ports:
      - 80:80
      - 444:443
      - 8080:8080
    configs:
      - source: ash-shell-profile
        target: ~/.profile
      - source: nginx-conf
        target: /etc/nginx/nginx.conf
      - source: proxy-conf
        target: /etc/nginx/proxy.conf

networks:
  proxynet:
    external: true

configs:
  ash-shell-profile:
    file: ./includes/.profile
  nginx-conf:
    file: ./includes/nginx.conf
  proxy-conf:
    file: ./includes/proxy.conf
